#!/bin/bash
if [[ -f ~/.config/wgu/config ]]; then
  source ~/.config/wgu/config
elif [[ -f ~/.wgu_config ]]; then
  source ~/.wgu_config
fi
: "${WG_DIR:=/etc/wireguard}"
wgquicks=$(sudo wg|grep 'interface:'|sed 's/interface: //')
if [[ -z $wgquicks ]]; then
  echo 'no wg up'
  exit 1
else
  for wgquick in $wgquicks; do
    sudo wg
    sudo wg-quick down ${WG_DIR}/${wgquick}.conf
  done
fi
