#!/bin/bash
if [[ -f ~/.config/wgu/config ]]; then
  source ~/.config/wgu/config
elif [[ -f ~/.wgu_config ]]; then
  source ~/.wgu_config
fi
: "${WG_DIR:=/etc/wireguard}"

# Safely read active WireGuard interfaces into an array
mapfile -t active_interfaces < <(sudo wg | grep 'interface:' | sed 's/interface: //')

if [[ ${#active_interfaces[@]} -eq 0 ]]; then
  if [[ ${VERBOSITY} -gt 6 ]]; then
    echo 'no wg up'
  fi
  exit 0
else
  for interface in "${active_interfaces[@]}"; do
    if [[ ${VERBOSITY} -gt 8 ]]; then
      echo $interface
    fi
    if [[ ${VERBOSITY} -gt 7 ]]; then
      echo $WG_DIR
    fi
    # Apply the selected configuration
    WG_CMD="sudo wg-quick down ${WG_DIR}/${interface}.conf"
    if [[ ${VERBOSITY} -gt 9 ]]; then
      $WG_CMD
    else
      $WG_CMD &> /dev/null
    fi
  done
fi
