#!/bin/bash
if [[ -f ~/.config/wgu/config ]]; then
  source ~/.config/wgu/config
elif [[ -f ~/.wgu_config ]]; then
  source ~/.wgu_config
fi
: "${WG_DIR:=/etc/wireguard}"

# Safely read active WireGuard interfaces into an array
mapfile -t active_interfaces < <(sudo wg | grep 'interface:' | sed 's/interface: //')

if [[ ${#active_interfaces[@]} -eq 0 ]]; then
  echo 'no wg up'
  exit 1
else
  for interface in "${active_interfaces[@]}"; do
    sudo wg-quick down "${WG_DIR}/${interface}.conf"
  done
fi
